- name: Enable epel repo
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/7/x86_64/
    gpgkey: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7

- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages }}"

- name: Deploy app
  copy:
    dest: /usr/share/nginx/html/
    src: index.html
